[package]
name = "osimodel"
version = "0.1.0"
edition = "2024"
description = ""
authors = [ "minghu6 <a19678zy@163.com>" ]

[features]
default = ["full"]
# default = ["parse"]
parse = ["dep:m6parsing"]
http = ["dep:cookie", "dep:mime", "dep:http"]
full = ["parse", "http"]

[dependencies]
m6tobytes = { path = "../m6coll/m6tobytes" }
derive_more = { version = "1.0.0", features = ["display", "error"] }

# optional http
cookie = { version = "0.18", optional = true }
mime = { version = "0.3", optional = true }
http = { version = "1.0", optional = true }

# optional parse
m6parsing = { path = "../m6coll/m6parsing", optional = true }


[dev-dependencies]
